#! /c/RailsInstaller/Ruby2.3.3/bin/ruby

require 'optparse'

require_relative './runner'
require_relative './utils/config'

require_relative './pages/page'
require_relative './pages/search_page'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: searcher -s search_engine -k keyword"

  opts.on("-s", "--search [name]", String, "name the search engine") do |name|
    options[:search_engine] = name
  end

  opts.on("-k", "--keyword [string]", String, "name the keyword") do |string|
    options[:keyword] = string
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

Runner.new(options).run!
