---
  allowed_search_engines:
    - google
    - bing
    - duck
  google_search_url: https://www.google.com
  bing_search_url: https://www.bing.com
  duck_search_url: https://duckduckgo.com
  default_sleep_value: 5
